### ISSUE TITLE
MessageBody annotation not taken into consideration - Kafka producer

### ISSUE THREAD

**Issue by yazidaqel** [micronaut-projects/micronaut-kafka#368]
Based on the javadoc @Body is deprecated and @MessageBody should be used instead,  but if used body content is not interpreted and an exception get fired.

### Task List

- [x] Steps to reproduce
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below) 

### Steps to Reproduce

1. Invoke kafka producer annotated with @MessageBody

### Expected Behaviour

Message should be sent to kafka

### Actual Behaviour

Exception raised
io.micronaut.messaging.exceptions.MessagingClientException: No valid message body argument found for method:

### Environment Information

- **Operating System**: ubuntu 20.04
- **Micronaut Version:** 2.5.1
- **JDK Version:** 11.0.11+9-Ubuntu-0ubuntu2.20.04

**Comment by yazidaqel** [comment]
I think the fix should be made at this level:
```
 if (ProducerRecord.class.isAssignableFrom(argument.getType()) || argument.isAnnotationPresent(Body.class)) {
                    bodyArgument = argument;
                    value = parameterValues[i];
                }

```

**Comment by guillermocalvo** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-kafka/pull/392
